name: flutter_race_view
description: A Flutter library which includes an animated bar chart race of all entities in a data set.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ^3.7.12

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
